name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Run at midnight every day
  workflow_dispatch:  # Allow manual triggering

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Necessary permission for pushing changes
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: assets/snake.svg
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
