name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Create assets folder
        run: mkdir -p assets

      - name: Generate Snake
        uses: Platane/snk@v3  # Version spécifique testée
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: assets/snake.svg

      - name: Debug file check
        run: |
          ls -la
          ls -la assets/

      - name: Commit and Push
        uses: EndBug/add-and-commit@v9
        with:
          add: assets/snake.svg
          message: "Update snake"
          github_token: ${{ secrets.GITHUB_TOKEN }}
