name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: assets/github-snake.svg  # Chemin modifié

      - name: Commit and Push
        uses: EndBug/add-and-commit@v9
        with:
          add: assets/github-snake.svg
          message: 'Update snake'
          new_branch: main  # 'branch' est devenu 'new_branch'
          github_token: ${{ secrets.GITHUB_TOKEN }}
